---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 3 workers
nodes:
  # the control plane node config
  - role: control-plane
    image: kindest/node:v1.35.0
  # the three workers
  - role: worker
    image: kindest/node:v1.35.0
  - role: worker
    image: kindest/node:v1.35.0
  - role: worker
    image: kindest/node:v1.35.0
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
